# Hexapod Visualizer Configuration File

# Serial Communication Settings
serial:
  port: "COM5"          # Serial port to connect to
  baudrate: 115200      # Baud rate for serial communication
  timeout: 1.0          # Read timeout in seconds

# Robot Physical Configuration
robot:
  # Body dimensions (for reference, not used in calculations)
  body:
    length: 0.200       # Body length in meters (front to back)
    width: 0.150        # Body width in meters (left to right)
    height: 0.050       # Body height in meters

  # Leg Configuration (6 legs total)
  # Each leg defined by its attachment point in body coordinates and rotation
  legs:
    # Left side legs (0, 1, 2)
    0:  # Left Front
      name: "Left Front"
      position: [0.08, 0.05, 0.0]        # Updated offsets: X front=+0.08, Y left=+0.05
      rotation: 0.7854                   # Rotation from body X-axis in radians (pi/4 = 45°)
      link_lengths: [0.068, 0.088, 0.127]   # [coxa, femur, tibia] lengths in meters
      joint_angle_offsets: [0.0, 0.5396943301595464, 1.0160719600939494]  # Offsets (coxa,femur,tibia)
      
    1:  # Left Middle  
      name: "Left Middle"
      position: [0.0, 0.05, 0.0]         # Middle X=0, left Y=+0.05
      rotation: 1.5708                   # Rotation from body X-axis in radians (pi/2 = 90°)
      link_lengths: [0.068, 0.088, 0.127]
      joint_angle_offsets: [0.0, 0.5396943301595464, 1.0160719600939494]
      
    2:  # Left Back
      name: "Left Back"
      position: [-0.08, 0.05, 0.0]       # Rear X=-0.08, left Y=+0.05
      rotation: 2.3562                   # Rotation from body X-axis in radians (3*pi/4 = 135°)
      link_lengths: [0.068, 0.088, 0.127]
      joint_angle_offsets: [0.0, 0.5396943301595464, 1.0160719600939494]

    # Right side legs (3, 4, 5)  
    3:  # Right Front
      name: "Right Front"
      position: [0.08, -0.05, 0.0]       # Front X=+0.08, right Y=-0.05
      rotation: -0.7854                  # Rotation from body X-axis in radians (-pi/4 = -45°)
      link_lengths: [0.068, 0.088, 0.127]
      joint_angle_offsets: [0.0, 0.5396943301595464, 1.0160719600939494]
      
    4:  # Right Middle
      name: "Right Middle" 
      position: [0.0, -0.05, 0.0]        # Middle X=0, right Y=-0.05
      rotation: -1.5708                  # Rotation from body X-axis in radians (-pi/2 = -90°)
      link_lengths: [0.068, 0.088, 0.127]
      joint_angle_offsets: [0.0, 0.5396943301595464, 1.0160719600939494]
      
    5:  # Right Back
      name: "Right Back"
      position: [-0.08, -0.05, 0.0]      # Rear X=-0.08, right Y=-0.05
      rotation: -2.3562                  # Rotation from body X-axis in radians (-3*pi/4 = -135°)
      link_lengths: [0.068, 0.088, 0.127]
      joint_angle_offsets: [0.0, 0.5396943301595464, 1.0160719600939494]

# Visualization Settings
visualization:
  # Real-time display settings
  update_rate: 60       # Target FPS for visualization updates
  buffer_size: 100      # Number of recent data points to keep in memory
  
  # Display options
  show_body: true       # Show robot body outline
  show_legs: true       # Show leg positions and orientations
  show_coordinates: true # Show coordinate system axes
  show_joints: true       # Show joints chain (coxa, femur, tibia)
  show_joint_angles: true # Annotate joint angles
  
  # Colors (RGB values 0-255)
  colors:
    body: [100, 100, 100]
    legs: [50, 150, 200]
    coordinates: [255, 0, 0]
    joints: [255, 215, 0]

# Data Processing Settings
data:
  # Coordinate system transformations
  coordinate_system: "right_hand"  # "right_hand" or "left_hand"
  units: "meters"                  # "meters" or "millimeters"
  
  # Filtering options
  enable_smoothing: false          # Apply smoothing filter to data
  smoothing_window: 5              # Number of samples for moving average (if enabled)